In [2]:
import tensorflow as tf
# Tensorflow -> Optimization for Deep learning


a = tf.constant([1, 2, 3])
b = tf.constant([4, 5, 6])

A = a + b
B = a*b

In [3]:
A

<tf.Tensor 'add_1:0' shape=(3,) dtype=int32>

In [4]:
B

<tf.Tensor 'mul_1:0' shape=(3,) dtype=int32>

In [5]:
# Session

sess = tf.Session()
sess.run(A)

array([5, 7, 9])

In [6]:
sess.run(B)

array([ 4, 10, 18])

In [16]:
w = tf.Variable([1, 1]) 
# decision variable in optimization
#  w has no value아직 아무런 값이 없음
# 초기값이 필요하기 때문에, 무조건 initialization이 필요.
init = tf.global_variables_initializer() # 모든 variable 초기화
sess.run(init) 

#sess.run(w)

array([1, 1])

In [18]:
# network에서 학습할때, input과 output이 동시에 필요함(supervised)
# tensorflow에서는 input과 output이 들어갈 공간을 미리 정해두어야함

x = tf.placeholder(tf.float32, [2, 2])

sess.run(x, feed_dict={x : [[1,2], [3,4]]})

array([[1., 2.],
       [3., 4.]], dtype=float32)